#!/bin/sh
make
echo -e "\n/// Complete Handler and Addition ///"
./mmu_manager 1 0 | tee /dev/stderr | ./oracle
echo -e "\n/// Complete Handler and Multiplication ///"
./mmu_manager 1 1 | tee /dev/stderr | ./oracle
